import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./openapi.gen"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
	baseUrl: import.meta.env.DEV ? "" : import.meta.env.VITE_API_BASE_URL,
});

export const $api = createClient(fetchClient);

// biome-ignore lint/suspicious/noExplicitAny: ignore
export const bodySerializer = (body: any) => {
	const formData = new FormData();
	if (body) {
		for (const key in body) {
			const data = body[key];
			if (data) {
				if (data instanceof File) {
					formData.append(key, data, encodeURI(data.name));
				} else {
					formData.append(key, data);
				}
			}
		}
	}
	return formData;
};
