import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./openapi.gen"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
	baseUrl: import.meta.env.DEV
		? "http://localhost:5173"
		: import.meta.env.VITE_API_BASE_URL,
});

export const $api = createClient(fetchClient);
