[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "edmkit>=0.0.7",
    "edmkit-search>=0.0.1a1",
    "fastapi[standard]>=0.118.0",
    "numpy>=2.4.4",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
    "python-multipart>=0.0.20",
    "typeid-python>=0.3.2",
]

[dependency-groups]
dev = ["ruff>=0.13.3", "ty>=0.0.1a21"]

[tool.uv]
prerelease = "allow"
