[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "MDE",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
    "python-multipart>=0.0.20",
    "typeid-python>=0.3.2",
]

[dependency-groups]
dev = ["ruff>=0.13.3", "ty>=0.0.1a21"]

[tool.uv.workspace]
members = ["MDE"]

[tool.uv.sources]
MDE = { workspace = true }
